baseURL: https://yatesdev.github.io/career-expo-talk
languageCode: en-us
title: Coppin Academy Career Expo
theme: PaperMod

googleAnalytics: G-KQXNBZX5SY
enableEmoji: true
params:
  homeInfoParams:
    Title: Hi, I'm Mike Yates
    Content: Software Engineer #Can be Info, links, about...

  socialIcons:
    - name: "email"
      url: "mailto:yates2+coppincareerexpo@umbc.edu"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/yatesdev/"
    - name: "github"
      url: "https://github.com/yatesdev"
  cover:
    hiddenInList: true
  hideFooter: true
  hideSummary: true
  ShowPostNavLinks: true