baseURL: https://yatesdev.github.io/poly-cs-talk
languageCode: en-us
title: Poly CS Talk
theme: PaperMod

googleAnalytics: G-KQXNBZX5SY
enableEmoji: true
params:
  homeInfoParams:
    Title: Hi, I'm Mike Yates
    Content: #Can be Info, links, about...

  socialIcons: # optional
    - name: "email"
      url: "mailto:mikehyates+polycs@gmail.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/yatesdev/"
  
  cover:
    hiddenInList: true
  hideFooter: true
  hideSummary: true
  